services:
  - type: web
    name: one-front-door
    runtime: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python backend/main.py"
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: PORT
        value: 10000
